-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: Sample

local fb = require('flatbuffers')
local N = fb.N

local Monster = {} -- the module

Monster.__New = fb.New(Monster)

Monster.pos = fb.GetSubFun(4,'MyGame.Sample.Vec3',false)

Monster.mana = fb.GetFieldFun(6,N.Int16,150)

Monster.hp = fb.GetFieldFun(8,N.Int16,100)

Monster.name = fb.GetStringFun(10)

Monster.inventory = fb.GetArrayFun(14,N.Uint8,1,'_fb_inventory_arr',0)

Monster.color = fb.GetFieldFun(16,N.Int8,2)

Monster.weapons = fb.GetArraySubFun(18,'MyGame.Sample.Weapon',4,'_fb_weapons_arr',true)

Monster.equipped_type = fb.GetFieldFun(20,N.Uint8,0)

Monster.equipped = fb.GetUnionFun(22)

Monster.path = fb.GetArraySubFun(24,'MyGame.Sample.Vec3',12,'_fb_path_arr',false)

Monster.isnpc = fb.GetFieldFunBool(26,N.Bool,false)


return Monster -- return the module
