-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: Sample

local fb = require('flatbuffers')
local N = fb.N

local Vec3 = {} -- the module

Vec3.__New = fb.New(Vec3)

function Vec3:x()
    return self.__view:Get(N.Float32, self.__view.pos + 0)
end
function Vec3:y()
    return self.__view:Get(N.Float32, self.__view.pos + 4)
end
function Vec3:z()
    return self.__view:Get(N.Float32, self.__view.pos + 8)
end

return Vec3 -- return the module