-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: Sample

local fb = require('flatbuffers')
local N = fb.N
local F=fb.F

local Weapon = F.NewCfg()

Weapon.name = F.FunFieldString(4)

Weapon.damage = F.FunField(6,N.Int16,0)


return Weapon -- return the module