-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: Sample

local fb = require('flatbuffers')
local N = fb.N

local Weapon = {} -- the module

Weapon.__New = fb.New(Weapon)

Weapon.name = fb.GetStringFun(4)

Weapon.damage = fb.GetFieldFun(6,N.Int16,0)


return Weapon -- return the module