// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyGame.Sample
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct MonsterRoot : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static MonsterRoot GetRootAsMonsterRoot(ByteBuffer _bb) { return GetRootAsMonsterRoot(_bb, new MonsterRoot()); }
  public static MonsterRoot GetRootAsMonsterRoot(ByteBuffer _bb, MonsterRoot obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MonsterRoot __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public MyGame.Sample.Monster? Items(int j) { int o = __p.__offset(4); return o != 0 ? (MyGame.Sample.Monster?)(new MyGame.Sample.Monster()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ItemsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<MyGame.Sample.MonsterRoot> CreateMonsterRoot(FlatBufferBuilder builder,
      VectorOffset itemsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    MonsterRoot.AddItems(builder, itemsOffset);
    return MonsterRoot.EndMonsterRoot(builder);
  }

  public static void StartMonsterRoot(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddItems(FlatBufferBuilder builder, VectorOffset itemsOffset) { builder.AddOffset(0, itemsOffset.Value, 0); }
  public static VectorOffset CreateItemsVector(FlatBufferBuilder builder, Offset<MyGame.Sample.Monster>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateItemsVectorBlock(FlatBufferBuilder builder, Offset<MyGame.Sample.Monster>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartItemsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<MyGame.Sample.MonsterRoot> EndMonsterRoot(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MyGame.Sample.MonsterRoot>(o);
  }
  public static void FinishMonsterRootBuffer(FlatBufferBuilder builder, Offset<MyGame.Sample.MonsterRoot> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedMonsterRootBuffer(FlatBufferBuilder builder, Offset<MyGame.Sample.MonsterRoot> offset) { builder.FinishSizePrefixed(offset.Value); }
}


}
